site_name: nftport_task
site_description: nftport backend task
repo_url: https://github.com/maxshilov/nftport_task
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/maxshilov">maxshilov</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
