# Generated by Django 3.1.13 on 2021-11-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='metadata_url',
            field=models.CharField(max_length=255),
        ),
    ]
